version: '3.0'
services:
  middleware:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CURR_ENV=local
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./middleware:/usr/local/eka/middleware
      - ./logs/middleware:/logs
    stdin_open: true
    tty: true
    command:
      - sh
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8080

  mysql:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_DATABASE: 'ekacare'
    expose:
      - 3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
