version: '3.1'
services:
  middleware:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080

    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./middleware:/usr/local/eka/middleware
      - ./logs/middleware:/logs
    stdin_open: true
    tty: true

  mysql:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ''
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'true'
      MARIADB_USER: 'root'
      MARIADB_PASSWORD: ''
      MARIADB_DATABASE: 'ekacare'
    expose:
      - 3306
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
