name: docker-hub-push

on:
  push:
    tags:
      - prod-*

env:
  DOCKER_REGISTRY: ekacare
  DOCKER_REPO: ${{ github.event.repository.name }}
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}         

      - name: Get the version
        id: get_version
        run: echo VERSION=$(echo $GITHUB_REF | cut -d / -f 3) >> $GITHUB_OUTPUT
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug        
          
      - name: Docker Build
        id: docker-build
        env:
          IMAGE_TAG: ${{ steps.get_version.outputs.VERSION }}
        run: |
          docker buildx build --platform $PLATFORMS -t $DOCKER_REGISTRY/$DOCKER_REPO:$IMAGE_TAG --push -f Dockerfile .

      # - name: Show image digest
      #   env:
      #     IMAGE_TAG: ${{ steps.get_version.outputs.VERSION }}
      
      #   run: |
      #     docker buildx imagetools inspect $IMAGE_TAG
